include:
  - project: 'Infrastructure/openshift-images/ci-templates'
    file: '/buildah.yml'

staging:
  extends:
    - .buildah
  variables:
    OCI_IMAGE_NAME: devdocsgjs
    OCI_IMAGE_TAG: staging

promote:
  interruptible: true
  image:
    name: quay.io/buildah/stable:latest
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_ISOLATION: chroot
  script:
    - buildah pull quay.io/gnome_infrastructure/devdocsgjs:staging
    - buildah tag quay.io/gnome_infrastructure/devdocsgjs:staging quay.io/gnome_infrastructure/devdocsgjs:latest
    - buildah push quay.io/gnome_infrastructure/devdocsgjs:latest
