include:
  - project: 'Infrastructure/openshift-images/ci-templates'
    file: '/buildah.yml'

staging:
  extends:
    - .buildah
  variables:
    OCI_IMAGE_NAME: devdocsgjs
    OCI_IMAGE_TAG: staging

promote:
  interruptible: true
  image:
    name: quay.io/buildah/stable:latest
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_ISOLATION: chroot
  script:
    - buildah pull quay.io/gnome_infrastructure/devdocsgjs:staging
    - buildah tag quay.io/gnome_infrastructure/devdocsgjs:staging quay.io/gnome_infrastructure/devdocsgjs:latest
    - >-
      if [ "$CI_COMMIT_REF_PROTECTED" == "true" ]; then
        buildah login -u ${OCI_REGISTRY_USER} -p ${OCI_REGISTRY_PASSWORD} ${OCI_REGISTRY}
        buildah push quay.io/gnome_infrastructure/devdocsgjs:latest
      fi
